### ISSUE TITLE
Any plans to update this project?

### ISSUE THREAD

**Issue by sudhashbahu** [evoluteur/evolutility-asp.net#1]
The ASP.NET version of Evolutility is more mature than the recent Evolutility-UI and Evolutility-Server projects. For example we have mater-detail capability, app generation wizard etc.

Are there any plans to continue work on this stream or has it been abandoned in favour of the newer ones?

**Comment by evoluteur** [comment]
Unfortunately I can't find the time to work on it anymore.

**Comment by sudhashbahu** [comment]
Thanks for the quick response. Do you plan to include the missing features in to the newer projects?

**Comment by evoluteur** [comment]
I have a design in mind for more than just matching the ASP.net features but also much more.
Unless I find a company who hires me to work on it, I'm not sure I can find the time to ever finish.
