### ISSUE TITLE
Is there a metadata generator?

### ISSUE THREAD

**Issue by landall** [evoluteur/evolutility-asp.net#2]
Must I write a xml handily or there is a generator for it?

**Comment by evoluteur** [comment]
There is a metadata generator. To use it you must store the metadata in the DB (it's possible to export it to XML later). Run the web site and go to the /EvoDico/EvoDicoWiz.aspx page.

**Comment by landall** [comment]
Thanks. Glad to find this great work.
It is very difficult to find such framework. maybe you should add some more feature to the name of this project, such as no-coding CRUD website generator or generate a multi-user CRUD web application from your database.
^_^
